services:
  - type: web
    name: tollipop-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: "8551305615:AAEdnWWsmqoWTT_pqiCQd-qO__LyVK7HG8E"
      - key: ADMIN_ID
        value: "5728569894"  # PALITAN MO ITO NG ID MO
