services:
  - type: web
    name: tollipop-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8551305615:AAEdnWWsmqoWTT_pqiCQd-qO__LyVK7HG8E"
      - key: ADMIN_ID
        value: "5728569894"  # PALITAN MO ITO NG ID MO
      - key: RENDER
        value: "true"
